/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.istloja.vistas;

import com.istloja.modelo.Persona;
import com.istloja.modelo.Inventario;
import com.istloja.modelo.Proveedores;
import javax.swing.JOptionPane;
import com.istloja.utilidad.Utilidades;
import com.istloja.controlador.Inventariobd;
import com.istloja.controlador.Proveedoresbd;
import com.istloja.controlador.personabd;
import com.istloja.modelTables.ComunicacionVistaModelosTablas;
import com.istloja.modelTables.ModelTablePersona;
import com.istloja.modelTables.ModelTableProveedores;
import com.istloja.modelTables.ModelTableInventario;
import java.awt.event.MouseEvent;
import java.util.List;

/**
 *
 * @author Ordenador
 */
public class GestionContable extends javax.swing.JFrame implements ComunicacionVistaModelosTablas {

    private Utilidades utilidades;
    private personabd controladorpersona;
    private Persona personaEditarEliminar;
    private Inventario inventarioeditar;
    private GestionContable gestioncontable;
    private Inventariobd controladorinventario;
    private Proveedores proveedoreditar;
    private Proveedoresbd controladorproveedor;
    private ModelTablePersona modelTablePersona;
    private ModelTableProveedores modelTableProveedor;
    private ModelTableInventario modelTableInventario;

    /**
     * Creates new form GestionContableV2
     */
    public GestionContable() {
        utilidades = new Utilidades();
        controladorpersona = new personabd();
        controladorinventario = new Inventariobd();
        controladorproveedor = new Proveedoresbd();
        modelTablePersona = new ModelTablePersona(controladorpersona.Obtenerpersonas(), this);
        modelTableProveedor = new ModelTableProveedores(controladorproveedor.obtenerProveedores(), this);
        modelTableInventario = new ModelTableInventario(controladorinventario.ObtenerInventario(), this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPersona = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDatosPersona = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedulaPersona = new javax.swing.JTextField();
        txtNombrePersona = new javax.swing.JTextField();
        txtApellidoPersona = new javax.swing.JTextField();
        txtDireccionPersona = new javax.swing.JTextField();
        txtCorreoPersona = new javax.swing.JTextField();
        txtTelefonoPersona = new javax.swing.JTextField();
        btnGuardarPersona = new javax.swing.JButton();
        btnEditarPersona = new javax.swing.JButton();
        btnEliminarPersona = new javax.swing.JButton();
        cmbBoxPersona = new javax.swing.JComboBox<>();
        txtBuscarPersona = new javax.swing.JTextField();
        btnBuscarPersona = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablePersona = new javax.swing.JTable();
        btnComprobarCedula = new javax.swing.JButton();
        jPanelProveedores = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtRucProveedor = new javax.swing.JTextField();
        txtRazonSocialProveedor = new javax.swing.JTextField();
        txtTipoActividadProveedor = new javax.swing.JTextField();
        txtNombreRepresentanteLEgalProveedor = new javax.swing.JTextField();
        txtApellidoRepresentanteLegalProveedor = new javax.swing.JTextField();
        txtTelefonoProveedor = new javax.swing.JTextField();
        txtCorreoProveedor = new javax.swing.JTextField();
        btnGuardarProveedor = new javax.swing.JButton();
        btnEditarProveedor = new javax.swing.JButton();
        btnEliminarProveedor = new javax.swing.JButton();
        cmbbBoxProveedores = new javax.swing.JComboBox<>();
        txtBuscarProveedor = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableProveedor = new javax.swing.JTable();
        jPanelInventario = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCodigoProductoInventario = new javax.swing.JTextField();
        txtPrecioCompraInventario = new javax.swing.JTextField();
        txtDescripcionInventario = new javax.swing.JTextField();
        txtPrecioVentaInventario = new javax.swing.JTextField();
        txtCantidadProductosInventario = new javax.swing.JTextField();
        btnGuardarInventario = new javax.swing.JButton();
        btnBuscarInventario = new javax.swing.JButton();
        btnEditarInventario = new javax.swing.JButton();
        btnEliminarInventario = new javax.swing.JButton();
        cmbBoxInventario = new javax.swing.JComboBox<>();
        txtBuscarInventario = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelVentas = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        SubmenuSalir = new javax.swing.JMenuItem();
        SubmenuAccionPersona = new javax.swing.JMenu();
        SubmenuBuscar = new javax.swing.JMenuItem();
        MenuEditar = new javax.swing.JMenu();
        MenuAcercade = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Personas");

        jPanelDatosPersona.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Persona"));

        jLabel2.setText("Cedula:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Direccion:");

        jLabel6.setText("Correo:");

        jLabel7.setText("Telefono:");

        javax.swing.GroupLayout jPanelDatosPersonaLayout = new javax.swing.GroupLayout(jPanelDatosPersona);
        jPanelDatosPersona.setLayout(jPanelDatosPersonaLayout);
        jPanelDatosPersonaLayout.setHorizontalGroup(
            jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCorreoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDireccionPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtApellidoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCedulaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelDatosPersonaLayout.setVerticalGroup(
            jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCedulaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccionPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtCorreoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnGuardarPersona.setText("Guardar");
        btnGuardarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPersonaActionPerformed(evt);
            }
        });

        btnEditarPersona.setText("Editar");
        btnEditarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPersonaActionPerformed(evt);
            }
        });

        btnEliminarPersona.setText("Eliminar");
        btnEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonaActionPerformed(evt);
            }
        });

        cmbBoxPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Telefono", " " }));

        btnBuscarPersona.setText("Buscar");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });

        TablePersona.setModel(modelTablePersona);
        jScrollPane3.setViewportView(TablePersona);

        btnComprobarCedula.setText("Comprobar Cedula");
        btnComprobarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarCedulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPersonaLayout = new javax.swing.GroupLayout(jPanelPersona);
        jPanelPersona.setLayout(jPanelPersonaLayout);
        jPanelPersonaLayout.setHorizontalGroup(
            jPanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnComprobarCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarPersona)
                .addGap(42, 42, 42)
                .addComponent(btnEditarPersona)
                .addGap(40, 40, 40)
                .addComponent(btnEliminarPersona)
                .addGap(58, 58, 58))
            .addGroup(jPanelPersonaLayout.createSequentialGroup()
                .addGroup(jPanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonaLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1))
                    .addGroup(jPanelPersonaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelDatosPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPersonaLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(cmbBoxPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPersona)))
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        jPanelPersonaLayout.setVerticalGroup(
            jPanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatosPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPersona)
                    .addComponent(btnEditarPersona)
                    .addComponent(btnEliminarPersona)
                    .addComponent(btnComprobarCedula))
                .addGap(18, 18, 18)
                .addGroup(jPanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Persona", jPanelPersona);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Proveedores");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Proveedor"));

        jLabel9.setText("RUC:");

        jLabel10.setText("Razon Social:");

        jLabel11.setText("Tipo Actividad:");

        jLabel12.setText("Nombre Representante Legal:");

        jLabel13.setText("Apellido Representante Legal");

        jLabel14.setText("Telefono:");

        jLabel15.setText("Correo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRazonSocialProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipoActividadProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreRepresentanteLEgalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoRepresentanteLegalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRazonSocialProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTipoActividadProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNombreRepresentanteLEgalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtApellidoRepresentanteLegalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        btnGuardarProveedor.setText("Guardar");
        btnGuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedorActionPerformed(evt);
            }
        });

        btnEditarProveedor.setText("Editar");
        btnEditarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProveedorActionPerformed(evt);
            }
        });

        btnEliminarProveedor.setText("Eliminar");
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });

        cmbbBoxProveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ruc", "Telefono" }));

        btnBuscarProveedor.setText("Buscar");
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });

        TableProveedor.setModel(modelTableProveedor);
        jScrollPane2.setViewportView(TableProveedor);

        javax.swing.GroupLayout jPanelProveedoresLayout = new javax.swing.GroupLayout(jPanelProveedores);
        jPanelProveedores.setLayout(jPanelProveedoresLayout);
        jPanelProveedoresLayout.setHorizontalGroup(
            jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(cmbbBoxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarProveedor)
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProveedoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarProveedor)
                        .addGap(29, 29, 29)
                        .addComponent(btnEditarProveedor)
                        .addGap(33, 33, 33)
                        .addComponent(btnEliminarProveedor)
                        .addGap(40, 40, 40))
                    .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProveedoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(318, 318, 318))
            .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelProveedoresLayout.setVerticalGroup(
            jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProveedor)
                    .addComponent(btnEditarProveedor)
                    .addComponent(btnEliminarProveedor))
                .addGap(18, 18, 18)
                .addGroup(jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbBoxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProveedor))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Proveedores", jPanelProveedores);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Inventario");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Inventario"));

        jLabel17.setText("Codigo Producto:");

        jLabel18.setText("Descripcion:");

        jLabel19.setText("Precio de Compra");

        jLabel20.setText("Precio de Venta");

        jLabel21.setText("Cantidad de Productos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodigoProductoInventario)
                    .addComponent(txtDescripcionInventario)
                    .addComponent(txtPrecioCompraInventario)
                    .addComponent(txtPrecioVentaInventario)
                    .addComponent(txtCantidadProductosInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCodigoProductoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtDescripcionInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtPrecioCompraInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtPrecioVentaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtCantidadProductosInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        btnGuardarInventario.setText("Guardar");
        btnGuardarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarInventarioActionPerformed(evt);
            }
        });

        btnBuscarInventario.setText("Buscar");
        btnBuscarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInventarioActionPerformed(evt);
            }
        });

        btnEditarInventario.setText("Editar");
        btnEditarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarInventarioActionPerformed(evt);
            }
        });

        btnEliminarInventario.setText("Eliminar");
        btnEliminarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInventarioActionPerformed(evt);
            }
        });

        cmbBoxInventario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo ", "Cantidad" }));

        jTable2.setModel(modelTableInventario);
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelInventarioLayout = new javax.swing.GroupLayout(jPanelInventario);
        jPanelInventario.setLayout(jPanelInventarioLayout);
        jPanelInventarioLayout.setHorizontalGroup(
            jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInventarioLayout.createSequentialGroup()
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInventarioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarInventario)
                        .addGap(60, 60, 60)
                        .addComponent(btnEditarInventario)
                        .addGap(41, 41, 41)
                        .addComponent(btnEliminarInventario))
                    .addGroup(jPanelInventarioLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(cmbBoxInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarInventario)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarInventario)))
                .addGap(36, 36, 36))
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelInventarioLayout.setVerticalGroup(
            jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarInventario)
                    .addComponent(btnEliminarInventario)
                    .addComponent(btnEditarInventario))
                .addGap(18, 18, 18)
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarInventario)
                    .addComponent(cmbBoxInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventario", jPanelInventario);

        javax.swing.GroupLayout jPanelVentasLayout = new javax.swing.GroupLayout(jPanelVentas);
        jPanelVentas.setLayout(jPanelVentasLayout);
        jPanelVentasLayout.setHorizontalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 782, Short.MAX_VALUE)
        );
        jPanelVentasLayout.setVerticalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Ventas", jPanelVentas);

        MenuArchivo.setText("Archivo");

        SubmenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SubmenuSalir.setText("Salir");
        SubmenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuSalirActionPerformed(evt);
            }
        });
        MenuArchivo.add(SubmenuSalir);

        SubmenuAccionPersona.setText("Accion Persona");

        SubmenuBuscar.setText("Buscar");
        SubmenuAccionPersona.add(SubmenuBuscar);

        MenuArchivo.add(SubmenuAccionPersona);

        jMenuBar1.add(MenuArchivo);

        MenuEditar.setText("Editar");
        jMenuBar1.add(MenuEditar);

        MenuAcercade.setText("Acerca de");
        jMenuBar1.add(MenuAcercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SubmenuSalirActionPerformed

    private void btnGuardarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPersonaActionPerformed
        guardareditarpersona();
        if (controladorpersona.Guardarpersona(guardareditarpersona())) {
            JOptionPane.showMessageDialog(rootPane, "Persona guardado con exito en el sistema");
            limpiarComponentesPersona();
            modelTablePersona.setPersonas(controladorpersona.Obtenerpersonas());
            modelTablePersona.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnGuardarPersonaActionPerformed

    private void btnGuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedorActionPerformed
        guardareditarproveedor();
        if (controladorproveedor.GuardarProveedor(guardareditarproveedor())) {
            JOptionPane.showMessageDialog(rootPane, "Proveedor guardado con exito en el sistema");
            limpiarComponentesProveedores();
            modelTableProveedor.setProvedores(controladorproveedor.obtenerProveedores());
            modelTableProveedor.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnGuardarProveedorActionPerformed

    private void btnGuardarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarInventarioActionPerformed
        guardareditarinventario();
        if (controladorinventario.GuardarInventario(guardareditarinventario())) {
            JOptionPane.showMessageDialog(rootPane, "Producto guardado con exito en el sistema");
            limpiarComponentesInventario();
            modelTableInventario.setInventario(controladorinventario.ObtenerInventario());
            modelTableInventario.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnGuardarInventarioActionPerformed

    private void btnComprobarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarCedulaActionPerformed
        if (!utilidades.validadorDeCedula(txtCedulaPersona.getText())) {
            JOptionPane.showMessageDialog(rootPane, "la cedula ingresada no es valida", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCedulaPersona.requestFocus();
        } else {
            JOptionPane.showMessageDialog(rootPane, "la cedula ingresada es valida");
            txtNombrePersona.requestFocus();
        }
    }//GEN-LAST:event_btnComprobarCedulaActionPerformed

    private void btnEditarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPersonaActionPerformed
        if (personaEditarEliminar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una Persona seleccionada para editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (personaEditarEliminar != null) {
            personaEditarEliminar = valoresactualizarPersona(personaEditarEliminar);
            if (controladorpersona.Editarpersona(personaEditarEliminar)) {
                JOptionPane.showMessageDialog(rootPane, "Persona editado con exito del sitema.");
                limpiarComponentesInventario();
                personaEditarEliminar = null;
                modelTablePersona.setPersonas(controladorpersona.Obtenerpersonas());
                modelTablePersona.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede editar la Persona", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarPersonaActionPerformed

    private void btnEditarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarInventarioActionPerformed
        if (inventarioeditar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una propducto seleccionado para editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (inventarioeditar != null) {
            inventarioeditar = valoresActualizarInventario(inventarioeditar);
            if (controladorinventario.EditarInventario(inventarioeditar)) {
                JOptionPane.showMessageDialog(rootPane, "Producto editado con exito del sitema.");
                limpiarComponentesInventario();
                inventarioeditar = null;
                modelTableInventario.setInventario(controladorinventario.ObtenerInventario());
                modelTableInventario.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede editar la Producto", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarInventarioActionPerformed

    private void btnEliminarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInventarioActionPerformed
        if (inventarioeditar != null) {
            if (controladorinventario.EliminarInventario(inventarioeditar)) {
                JOptionPane.showMessageDialog(rootPane, "Producto eliminado con éxito del sitema.");
                limpiarComponentesInventario();
                inventarioeditar = null;
                modelTableInventario.setInventario(controladorinventario.ObtenerInventario());
                modelTableInventario.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar el producto seleccionado.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay producto seleccionada para eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarInventarioActionPerformed

    private void btnEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonaActionPerformed
        if (personaEditarEliminar != null) {
            if (controladorpersona.Eliminarpersona(personaEditarEliminar)) {
                JOptionPane.showMessageDialog(rootPane, "Persona eliminada con éxito del sitema.");
                limpiarComponentesPersona();
                personaEditarEliminar = null;
                modelTablePersona.setPersonas(controladorpersona.Obtenerpersonas());
                modelTablePersona.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar la Persona seleccionado.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay Persona seleccionada para eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarPersonaActionPerformed

    private void btnEditarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProveedorActionPerformed
        if (proveedoreditar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una propducto seleccionado para editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (proveedoreditar != null) {
            proveedoreditar = valoresActualizarProveedor(proveedoreditar);
            if (controladorproveedor.EditarProveedor(proveedoreditar)) {
                JOptionPane.showMessageDialog(rootPane, "Producto editado con exito del sitema.");
                limpiarComponentesInventario();
                proveedoreditar = null;
                modelTableProveedor.setProvedores(controladorproveedor.obtenerProveedores());
                modelTableInventario.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede editar la Producto", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarProveedorActionPerformed

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed
        if (proveedoreditar != null) {
            if (controladorproveedor.EliminarProveedores(proveedoreditar)) {
                JOptionPane.showMessageDialog(rootPane, "Proveedor eliminada con éxito del sitema.");
                limpiarComponentesProveedores();
                proveedoreditar = null;
                modelTableProveedor.setProvedores(controladorproveedor.obtenerProveedores());
                modelTableProveedor.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar el Proveedor seleccionado.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay Proveedor seleccionado para eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed
        switch(cmbBoxPersona.getSelectedIndex()){
            case 0://Cedula
                modelTablePersona.setPersonas(controladorpersona.getPersonaCedulaLista(txtBuscarPersona.getText()));
                modelTablePersona.fireTableDataChanged();
                break;
            case 1://Telefono
                modelTablePersona.setPersonas(controladorpersona.getPersonaTelefonoLista(txtBuscarPersona.getText()));
                modelTablePersona.fireTableDataChanged();
                break;
        }
    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
       switch(cmbbBoxProveedores.getSelectedIndex()){
           case 0://Ruc
               modelTableProveedor.setProvedores(controladorproveedor.ObtenerProveedoresRucLista(txtBuscarProveedor.getText()));
               modelTableProveedor.fireTableDataChanged();
               break;
           case 1://Telefono
               modelTableProveedor.setProvedores(controladorproveedor.ObtenerProveedoresTelefono(txtBuscarProveedor.getText()));
               modelTableProveedor.fireTableDataChanged();
               break;
       }
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    private void btnBuscarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInventarioActionPerformed
        switch(cmbBoxInventario.getSelectedIndex()){
            case 0:
                modelTableInventario.setInventario(controladorinventario.ObtenerInventarioCodigoLista(txtBuscarInventario.getText()));
                modelTableInventario.fireTableDataChanged();
                break;
            case 1:
                modelTableInventario.setInventario(controladorinventario.ObtenerInventarioCantidadLista(txtBuscarInventario.getText()));
                modelTableInventario.fireTableDataChanged();
                break;
        }
    }//GEN-LAST:event_btnBuscarInventarioActionPerformed

    public Persona guardareditarpersona() {
        if (txtCedulaPersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo cedula no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCedulaPersona.requestFocus();
            return null;
        }
        if (!utilidades.validadorDeCedula(txtCedulaPersona.getText())) {
            JOptionPane.showMessageDialog(rootPane, "la cedula ingresada no es valida", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCedulaPersona.requestFocus();
            return null;
        }
        if (txtNombrePersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo nombres no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNombrePersona.requestFocus();
            return null;
        }
        if (txtApellidoPersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo apellidos no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtApellidoPersona.requestFocus();
            return null;
        }
        if (txtDireccionPersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo direccion no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtDireccionPersona.requestFocus();
            return null;
        }
        if (txtCorreoPersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo correo no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCorreoPersona.requestFocus();
            return null;
        }
//        if (!utilidades.validarcorreo(txtCorreoPersona.getText())) {
//            JOptionPane.showMessageDialog(rootPane, "El campo correo no tiene arroba", "ERROR", JOptionPane.ERROR_MESSAGE);
//            txtCorreoPersona.requestFocus();
//        }
        if (txtTelefonoPersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo telefono no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtTelefonoPersona.requestFocus();
            return null;
        }
//        if (!utilidades.validarNumeros(txtTelefonoPersona.getText())) {
//            JOptionPane.showMessageDialog(rootPane, "Los datos ingresados en el telefono no son validos.", "ERROR", JOptionPane.ERROR_MESSAGE);
//            txtTelefonoPersona.requestFocus();
//            return null;
//        }
        Persona persona = new Persona();
        persona.setCedula(txtCedulaPersona.getText());
        persona.setNombre(txtNombrePersona.getText());
        persona.setApellido(txtApellidoPersona.getText());
        persona.setDireccion(txtDireccionPersona.getText());
        persona.setTelefono(txtTelefonoPersona.getText());
        persona.setCorreo(txtCorreoPersona.getText());
        return persona;
    }

    private Persona valoresactualizarPersona(Persona pe) {
        pe.setCedula(txtCedulaPersona.getText());
        pe.setNombre(txtNombrePersona.getText());
        pe.setApellido(txtApellidoPersona.getText());
        pe.setDireccion(txtDireccionPersona.getText());
        pe.setCorreo(txtCorreoPersona.getText());
        pe.setTelefono(txtTelefonoPersona.getText());
        return pe;
    }

    public Proveedores guardareditarproveedor() {
        if (txtRucProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo RUC no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtRucProveedor.requestFocus();
            return null;
        }
        if (txtRazonSocialProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo Razon Social no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtRazonSocialProveedor.requestFocus();
            return null;
        }
        if (txtTipoActividadProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo Tipo de Actividad no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtTipoActividadProveedor.requestFocus();
            return null;
        }
        if (txtNombreRepresentanteLEgalProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo Nombre de representante legal no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNombreRepresentanteLEgalProveedor.requestFocus();
            return null;
        }
        if (txtApellidoRepresentanteLegalProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo Apellido de representante legal no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtApellidoRepresentanteLegalProveedor.requestFocus();
            return null;
        }
        if (txtTelefonoProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El telefono cedula no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtTelefonoProveedor.requestFocus();
            return null;
        }
        if (txtCorreoProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo correo no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCorreoProveedor.requestFocus();
            return null;
        }
        Proveedores provedor = new Proveedores();
        provedor.setRuc(txtRucProveedor.getText());
        provedor.setRazonSocial(txtRazonSocialProveedor.getText());
        provedor.setTipoActividad(txtTipoActividadProveedor.getText());
        provedor.setNombreRepresentanteLegal(txtNombreRepresentanteLEgalProveedor.getText());
        provedor.setApellidosRepresentanteLegal(txtApellidoRepresentanteLegalProveedor.getText());
        provedor.setTelefono(txtTelefonoProveedor.getText());
        provedor.setCorreo(txtCorreoProveedor.getText());
        return provedor;
    }

    public Proveedores valoresActualizarProveedor(Proveedores p) {
        p.setRuc(txtRucProveedor.getText());
        p.setRazonSocial(txtRazonSocialProveedor.getText());
        p.setTipoActividad(txtTipoActividadProveedor.getText());
        p.setNombreRepresentanteLegal(txtNombreRepresentanteLEgalProveedor.getText());
        p.setApellidosRepresentanteLegal(txtApellidoRepresentanteLegalProveedor.getText());
        p.setTelefono(txtTelefonoProveedor.getText());
        p.setCorreo(txtCorreoProveedor.getText());
        return p;
    }

    public Inventario guardareditarinventario() {
        if (txtCodigoProductoInventario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo codigo de producto no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCodigoProductoInventario.requestFocus();
            return null;
        }
        if (txtDescripcionInventario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo descripcion no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtDescripcionInventario.requestFocus();
            return null;
        }
        if (txtPrecioCompraInventario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo precio de compra no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtPrecioCompraInventario.requestFocus();
            return null;
        }
        if (txtPrecioVentaInventario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo precio de venta no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtPrecioVentaInventario.requestFocus();
            return null;
        }
        if (txtCantidadProductosInventario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo cantidad de prodictos no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCantidadProductosInventario.requestFocus();
            return null;
        }
        Inventario inventario = new Inventario();
        inventario.setCodigoProducto(txtCodigoProductoInventario.getText());
        inventario.setDescripcion(txtDescripcionInventario.getText());
        inventario.setPrecioCompra(txtPrecioCompraInventario.getText());
        inventario.setPrecioVenta(txtPrecioVentaInventario.getText());
        inventario.setCantidadProductos(txtCantidadProductosInventario.getText());
        return inventario;
    }

    private Inventario valoresActualizarInventario(Inventario i) {
        i.setCodigoProducto(txtCodigoProductoInventario.getText());
        i.setDescripcion(txtDescripcionInventario.getText());
        i.setPrecioCompra(txtPrecioCompraInventario.getText());
        i.setPrecioVenta(txtPrecioVentaInventario.getText());
        i.setCantidadProductos(txtCantidadProductosInventario.getText());
        return i;
    }

    public void limpiarComponentesPersona() {
        txtCedulaPersona.setText("");
        txtNombrePersona.setText("");
        txtApellidoPersona.setText("");
        txtDireccionPersona.setText("");
        txtTelefonoPersona.setText("");
        txtCorreoPersona.setText("");
    }

    public void limpiarComponentesProveedores() {
        txtRucProveedor.setText("");
        txtRazonSocialProveedor.setText("");
        txtTipoActividadProveedor.setText("");
        txtNombreRepresentanteLEgalProveedor.setText("");
        txtApellidoRepresentanteLegalProveedor.setText("");
        txtTelefonoProveedor.setText("");
        txtCorreoProveedor.setText("");
    }

    public void limpiarComponentesInventario() {
        txtCodigoProductoInventario.setText("");
        txtDescripcionInventario.setText("");
        txtPrecioCompraInventario.setText("");
        txtPrecioVentaInventario.setText("");
        txtCantidadProductosInventario.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionContable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAcercade;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuEditar;
    private javax.swing.JMenu SubmenuAccionPersona;
    private javax.swing.JMenuItem SubmenuBuscar;
    private javax.swing.JMenuItem SubmenuSalir;
    private javax.swing.JTable TablePersona;
    private javax.swing.JTable TableProveedor;
    private javax.swing.JButton btnBuscarInventario;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnComprobarCedula;
    private javax.swing.JButton btnEditarInventario;
    private javax.swing.JButton btnEditarPersona;
    private javax.swing.JButton btnEditarProveedor;
    private javax.swing.JButton btnEliminarInventario;
    private javax.swing.JButton btnEliminarPersona;
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnGuardarInventario;
    private javax.swing.JButton btnGuardarPersona;
    private javax.swing.JButton btnGuardarProveedor;
    private javax.swing.JComboBox<String> cmbBoxInventario;
    private javax.swing.JComboBox<String> cmbBoxPersona;
    private javax.swing.JComboBox<String> cmbbBoxProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelDatosPersona;
    private javax.swing.JPanel jPanelInventario;
    private javax.swing.JPanel jPanelPersona;
    private javax.swing.JPanel jPanelProveedores;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtApellidoPersona;
    private javax.swing.JTextField txtApellidoRepresentanteLegalProveedor;
    private javax.swing.JTextField txtBuscarInventario;
    private javax.swing.JTextField txtBuscarPersona;
    private javax.swing.JTextField txtBuscarProveedor;
    private javax.swing.JTextField txtCantidadProductosInventario;
    private javax.swing.JTextField txtCedulaPersona;
    private javax.swing.JTextField txtCodigoProductoInventario;
    private javax.swing.JTextField txtCorreoPersona;
    private javax.swing.JTextField txtCorreoProveedor;
    private javax.swing.JTextField txtDescripcionInventario;
    private javax.swing.JTextField txtDireccionPersona;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JTextField txtNombreRepresentanteLEgalProveedor;
    private javax.swing.JTextField txtPrecioCompraInventario;
    private javax.swing.JTextField txtPrecioVentaInventario;
    private javax.swing.JTextField txtRazonSocialProveedor;
    private javax.swing.JTextField txtRucProveedor;
    private javax.swing.JTextField txtTelefonoPersona;
    private javax.swing.JTextField txtTelefonoProveedor;
    private javax.swing.JTextField txtTipoActividadProveedor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clickPersona(Persona p) {
        personaEditarEliminar = p;
        txtCedulaPersona.setText(p.getCedula());
        txtNombrePersona.setText(p.getNombre());
        txtApellidoPersona.setText(p.getApellido());
        txtDireccionPersona.setText(p.getDireccion());
        txtTelefonoPersona.setText(p.getTelefono());
        txtCorreoPersona.setText(p.getCorreo());
    }

    @Override
    public void clickInventario(Inventario i) {
        inventarioeditar = i;
        txtCodigoProductoInventario.setText(i.getCodigoProducto());
        txtDescripcionInventario.setText(i.getDescripcion());
        txtPrecioCompraInventario.setText(i.getPrecioCompra());
        txtPrecioVentaInventario.setText(i.getPrecioVenta());
        txtCantidadProductosInventario.setText(i.getCantidadProductos());
    }

    @Override
    public void clickProveedores(Proveedores pr) {
        proveedoreditar = pr;
        txtRucProveedor.setText(pr.getRuc());
        txtRazonSocialProveedor.setText(pr.getRazonSocial());
        txtTipoActividadProveedor.setText(pr.getTipoActividad());
        txtNombreRepresentanteLEgalProveedor.setText(pr.getNombreRepresentanteLegal());
        txtApellidoRepresentanteLegalProveedor.setText(pr.getApellidosRepresentanteLegal());
        txtTelefonoProveedor.setText(pr.getTelefono());
        txtCorreoProveedor.setText(pr.getCorreo());
    }

}
