/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.istloja.vistas;

import com.istloja.modelo.Persona;
import com.istloja.modelo.Inventario;
import com.istloja.modelo.Proveedores;
import javax.swing.JOptionPane;
import com.istloja.utilidad.Utilidades;
import com.istloja.controlador.Inventariobd;
import com.istloja.controlador.Proveedoresbd;
import com.istloja.controlador.personabd;
import com.istloja.modelTables.ComunicacionVistaModelosTablas;
import com.istloja.modelTables.ModelTablePersona;
import com.istloja.modelTables.ModelTableProveedores;
import com.istloja.modelTables.ModelTableInventario;
import com.istloja.modelTables.ModelTableUsuario;
import com.istloja.modelo.TipoUsuario;
import com.istloja.controlador.tipousuariobd;




/**
 *
 * @author Ordenador
 */
public class GestionContable extends javax.swing.JFrame implements ComunicacionVistaModelosTablas {

    private Utilidades utilidades;
    private personabd controladorpersona;
    private Persona personaEditarEliminar;
    private Inventario inventarioeditar;
    private GestionContable gestioncontable;
    private Inventariobd controladorinventario;
    private Proveedores proveedoreditar;
    private Proveedoresbd controladorproveedor;
    private ModelTablePersona modelTablePersona;
    private ModelTableProveedores modelTableProveedor;
    private ModelTableInventario modelTableInventario;
    private ModelTableUsuario modelTableUsuario;
    private TipoUsuario usuarioeditar;
    private tipousuariobd controladorusuario;

    /**
     * Creates new form GestionContableV2
     */
    public GestionContable() {
        utilidades = new Utilidades();
        controladorpersona = new personabd();
        controladorinventario = new Inventariobd();
        controladorproveedor = new Proveedoresbd();
        controladorusuario = new tipousuariobd();
        modelTablePersona = new ModelTablePersona(controladorpersona.Obtenerpersonas(), this);
        modelTableProveedor = new ModelTableProveedores(controladorproveedor.obtenerProveedores(), this);
        modelTableInventario = new ModelTableInventario(controladorinventario.ObtenerInventario(), this);
        modelTableUsuario = new ModelTableUsuario(controladorusuario.ObtenerUsuarios(), this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPersona = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDatosPersona = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedulaPersona = new javax.swing.JTextField();
        txtNombrePersona = new javax.swing.JTextField();
        txtApellidoPersona = new javax.swing.JTextField();
        txtDireccionPersona = new javax.swing.JTextField();
        txtCorreoPersona = new javax.swing.JTextField();
        txtTelefonoPersona = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtGeneroPersona = new javax.swing.JTextField();
        rdbCedula = new javax.swing.JRadioButton();
        rdbPasaporte = new javax.swing.JRadioButton();
        btnGuardarPersona = new javax.swing.JButton();
        btnEditarPersona = new javax.swing.JButton();
        btnEliminarPersona = new javax.swing.JButton();
        cmbBoxPersona = new javax.swing.JComboBox<>();
        txtBuscarPersona = new javax.swing.JTextField();
        btnBuscarPersona = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablePersona = new javax.swing.JTable();
        btnComprobarCedula = new javax.swing.JButton();
        jPanelProveedores = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtRucProveedor = new javax.swing.JTextField();
        txtRazonSocialProveedor = new javax.swing.JTextField();
        txtTipoActividadProveedor = new javax.swing.JTextField();
        txtNombreRepresentanteLEgalProveedor = new javax.swing.JTextField();
        txtApellidoRepresentanteLegalProveedor = new javax.swing.JTextField();
        txtTelefonoProveedor = new javax.swing.JTextField();
        txtCorreoProveedor = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDireccionProveedor = new javax.swing.JTextField();
        btnGuardarProveedor = new javax.swing.JButton();
        btnEditarProveedor = new javax.swing.JButton();
        btnEliminarProveedor = new javax.swing.JButton();
        cmbbBoxProveedores = new javax.swing.JComboBox<>();
        txtBuscarProveedor = new javax.swing.JTextField();
        btnBuscarProveedor = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableProveedor = new javax.swing.JTable();
        jPanelInventario = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtCodigoProductoInventario = new javax.swing.JTextField();
        txtCantidadProductoInventario = new javax.swing.JTextField();
        txtDescripcionInventario = new javax.swing.JTextField();
        TxtComprasinIvatInventario = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        TxtCompraconIvaInventario = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TxtPrecioalMayorInventario = new javax.swing.JTextField();
        TxtPrecioFijoInventario = new javax.swing.JTextField();
        TxtPrecioNormalInventario = new javax.swing.JTextField();
        jDtCaducidadInventario = new com.toedter.calendar.JDateChooser();
        btnGuardarInventario = new javax.swing.JButton();
        btnBuscarInventario = new javax.swing.JButton();
        btnEditarInventario = new javax.swing.JButton();
        btnEliminarInventario = new javax.swing.JButton();
        cmbBoxInventario = new javax.swing.JComboBox<>();
        txtBuscarInventario = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelVentas = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        btnAgregarVentas = new javax.swing.JButton();
        txtNotaVentaVentas = new javax.swing.JTextField();
        txtCedulaoRucClienteVentas = new javax.swing.JTextField();
        txtProductoVentas = new javax.swing.JTextField();
        txtCantidadProductoVentas = new javax.swing.JTextField();
        txtNombreClienteVentas = new javax.swing.JTextField();
        txtTelefonoClienteVentas = new javax.swing.JTextField();
        txtFechaVentaVentas = new javax.swing.JTextField();
        txtDireccionClienteVentas = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableVentas = new javax.swing.JTable();
        jPanelUsuarios = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtTiposUsuariosUsuarios = new javax.swing.JTextField();
        txtIdUsuarioSistemaUsuario = new javax.swing.JTextField();
        txtContraseñaUsuario = new javax.swing.JTextField();
        btnGuardarUsuario = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaUsuario = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        SubmenuSalir = new javax.swing.JMenuItem();
        SubmenuAccionPersona = new javax.swing.JMenu();
        SubmenuBuscar = new javax.swing.JMenuItem();
        MenuEditar = new javax.swing.JMenu();
        MenuAcercade = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Personas");

        jPanelDatosPersona.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Persona"));

        jLabel2.setText("Cedula:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Direccion:");

        jLabel6.setText("Correo:");

        jLabel7.setText("Telefono:");

        jLabel22.setText("Genero:");

        rdbCedula.setText("Cedula");

        rdbPasaporte.setText("Pasaporte");

        javax.swing.GroupLayout jPanelDatosPersonaLayout = new javax.swing.GroupLayout(jPanelDatosPersona);
        jPanelDatosPersona.setLayout(jPanelDatosPersonaLayout);
        jPanelDatosPersonaLayout.setHorizontalGroup(
            jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCorreoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDireccionPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(txtApellidoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                            .addComponent(txtGeneroPersona))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCedulaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rdbCedula)
                        .addGap(18, 18, 18)
                        .addComponent(rdbPasaporte)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        jPanelDatosPersonaLayout.setVerticalGroup(
            jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCedulaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbCedula)
                    .addComponent(rdbPasaporte))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDireccionPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txtCorreoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtGeneroPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnGuardarPersona.setText("Guardar");
        btnGuardarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPersonaActionPerformed(evt);
            }
        });

        btnEditarPersona.setText("Editar");
        btnEditarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPersonaActionPerformed(evt);
            }
        });

        btnEliminarPersona.setText("Eliminar");
        btnEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonaActionPerformed(evt);
            }
        });

        cmbBoxPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Telefono", " " }));

        btnBuscarPersona.setText("Buscar");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });

        TablePersona.setModel(modelTablePersona);
        jScrollPane3.setViewportView(TablePersona);

        btnComprobarCedula.setText("Comprobar Cedula");
        btnComprobarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprobarCedulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPersonaLayout = new javax.swing.GroupLayout(jPanelPersona);
        jPanelPersona.setLayout(jPanelPersonaLayout);
        jPanelPersonaLayout.setHorizontalGroup(
            jPanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btnComprobarCedula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarPersona)
                .addGap(42, 42, 42)
                .addComponent(btnEditarPersona)
                .addGap(40, 40, 40)
                .addComponent(btnEliminarPersona)
                .addGap(58, 58, 58))
            .addGroup(jPanelPersonaLayout.createSequentialGroup()
                .addGroup(jPanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPersonaLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1))
                    .addGroup(jPanelPersonaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelDatosPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPersonaLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(cmbBoxPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarPersona)))
                .addContainerGap(155, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        jPanelPersonaLayout.setVerticalGroup(
            jPanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatosPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarPersona)
                    .addComponent(btnEditarPersona)
                    .addComponent(btnEliminarPersona)
                    .addComponent(btnComprobarCedula))
                .addGap(18, 18, 18)
                .addGroup(jPanelPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBoxPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Persona", jPanelPersona);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Proveedores");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Proveedor"));

        jLabel9.setText("RUC:");

        jLabel10.setText("Razon Social:");

        jLabel11.setText("Tipo Actividad:");

        jLabel12.setText("Nombre Representante Legal:");

        jLabel13.setText("Apellido Representante Legal");

        jLabel14.setText("Telefono:");

        jLabel15.setText("Correo:");

        jLabel23.setText("Direccion:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRazonSocialProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                                    .addComponent(txtRucProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                                    .addComponent(txtTipoActividadProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                                    .addComponent(txtNombreRepresentanteLEgalProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                                    .addComponent(txtApellidoRepresentanteLegalProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                                    .addComponent(txtDireccionProveedor)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreoProveedor)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtRucProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRazonSocialProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtTipoActividadProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNombreRepresentanteLEgalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtApellidoRepresentanteLegalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        btnGuardarProveedor.setText("Guardar");
        btnGuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedorActionPerformed(evt);
            }
        });

        btnEditarProveedor.setText("Editar");
        btnEditarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProveedorActionPerformed(evt);
            }
        });

        btnEliminarProveedor.setText("Eliminar");
        btnEliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProveedorActionPerformed(evt);
            }
        });

        cmbbBoxProveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ruc", "Telefono" }));

        btnBuscarProveedor.setText("Buscar");
        btnBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProveedorActionPerformed(evt);
            }
        });

        TableProveedor.setModel(modelTableProveedor);
        jScrollPane2.setViewportView(TableProveedor);

        javax.swing.GroupLayout jPanelProveedoresLayout = new javax.swing.GroupLayout(jPanelProveedores);
        jPanelProveedores.setLayout(jPanelProveedoresLayout);
        jPanelProveedoresLayout.setHorizontalGroup(
            jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(cmbbBoxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarProveedor)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProveedoresLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarProveedor)
                        .addGap(29, 29, 29)
                        .addComponent(btnEditarProveedor)
                        .addGap(33, 33, 33)
                        .addComponent(btnEliminarProveedor)
                        .addGap(40, 40, 40))
                    .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProveedoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(318, 318, 318))
            .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelProveedoresLayout.setVerticalGroup(
            jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProveedoresLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProveedor)
                    .addComponent(btnEditarProveedor)
                    .addComponent(btnEliminarProveedor))
                .addGap(18, 18, 18)
                .addGroup(jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbbBoxProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProveedor))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Proveedores", jPanelProveedores);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel16.setText("Inventario");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Inventario"));

        jLabel17.setText("Codigo Producto:");

        jLabel18.setText("Descripcion:");

        jLabel19.setText("Cantidad de Producto");

        jLabel20.setText("Fecha de Caducidad");

        jLabel21.setText("Precio deCompra");

        jLabel24.setText("Compra con Iva");

        jLabel25.setText("Precio mayorista: ");

        jLabel26.setText("Precio Fijo:");

        jLabel27.setText("Precio Normal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TxtComprasinIvatInventario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidadProductoInventario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcionInventario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoProductoInventario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtCompraconIvaInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addComponent(jDtCaducidadInventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPrecioalMayorInventario, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(31, 31, 31)
                        .addComponent(TxtPrecioFijoInventario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(TxtPrecioNormalInventario)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCodigoProductoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(TxtPrecioalMayorInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtDescripcionInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(TxtPrecioFijoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtCantidadProductoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(TxtPrecioNormalInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jDtCaducidadInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TxtComprasinIvatInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(TxtCompraconIvaInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnGuardarInventario.setText("Guardar");
        btnGuardarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarInventarioActionPerformed(evt);
            }
        });

        btnBuscarInventario.setText("Buscar");
        btnBuscarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarInventarioActionPerformed(evt);
            }
        });

        btnEditarInventario.setText("Editar");
        btnEditarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarInventarioActionPerformed(evt);
            }
        });

        btnEliminarInventario.setText("Eliminar");
        btnEliminarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarInventarioActionPerformed(evt);
            }
        });

        cmbBoxInventario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo ", "Cantidad" }));

        jTable2.setModel(modelTableInventario);
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanelInventarioLayout = new javax.swing.GroupLayout(jPanelInventario);
        jPanelInventario.setLayout(jPanelInventarioLayout);
        jPanelInventarioLayout.setHorizontalGroup(
            jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInventarioLayout.createSequentialGroup()
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelInventarioLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardarInventario)
                        .addGap(60, 60, 60)
                        .addComponent(btnEditarInventario)
                        .addGap(41, 41, 41)
                        .addComponent(btnEliminarInventario))
                    .addGroup(jPanelInventarioLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(cmbBoxInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarInventario)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarInventario)))
                .addGap(36, 36, 36))
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelInventarioLayout.setVerticalGroup(
            jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInventarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarInventario)
                    .addComponent(btnEliminarInventario)
                    .addComponent(btnEditarInventario))
                .addGap(18, 18, 18)
                .addGroup(jPanelInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarInventario)
                    .addComponent(cmbBoxInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Inventario", jPanelInventario);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel33.setText("NOTA VENTA");

        jLabel34.setText("NUMERO NOTA VENTA");

        jLabel35.setText("CEDULA O RUC CLIENTE");

        jLabel36.setText("NOMBRE CLIENTE");

        jLabel37.setText("TELEFONO");

        jLabel38.setText("DIRECCION");

        jLabel39.setText("FECHA VENTA");

        jLabel40.setText("PRODUCTO");

        jLabel41.setText("CANTIDAD");

        btnAgregarVentas.setText("Agregar");
        btnAgregarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVentasActionPerformed(evt);
            }
        });

        txtCedulaoRucClienteVentas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaoRucClienteVentasFocusLost(evt);
            }
        });

        txtNombreClienteVentas.setEditable(false);

        txtTelefonoClienteVentas.setEditable(false);

        txtFechaVentaVentas.setEditable(false);

        txtDireccionClienteVentas.setEditable(false);

        TableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(TableVentas);

        javax.swing.GroupLayout jPanelVentasLayout = new javax.swing.GroupLayout(jPanelVentas);
        jPanelVentas.setLayout(jPanelVentasLayout);
        jPanelVentasLayout.setHorizontalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentasLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelVentasLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                                .addComponent(txtTelefonoClienteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelVentasLayout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtProductoVentas))
                            .addGroup(jPanelVentasLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreClienteVentas)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelVentasLayout.createSequentialGroup()
                                .addComponent(jLabel41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCantidadProductoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnAgregarVentas)
                                .addGap(49, 49, 49))
                            .addGroup(jPanelVentasLayout.createSequentialGroup()
                                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVentasLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel39)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDireccionClienteVentas, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                                    .addComponent(txtFechaVentaVentas))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelVentasLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(18, 18, 18)
                                .addComponent(txtNotaVentaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelVentasLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCedulaoRucClienteVentas)))
                        .addGap(0, 41, Short.MAX_VALUE))))
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel33))
                    .addGroup(jPanelVentasLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelVentasLayout.setVerticalGroup(
            jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtNotaVentaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txtCedulaoRucClienteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel38)
                    .addComponent(txtNombreClienteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionClienteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel39)
                    .addComponent(txtFechaVentaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoClienteVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanelVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(btnAgregarVentas)
                    .addComponent(txtProductoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidadProductoVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ventas", jPanelVentas);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setText("Usuarios");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Usuarios"));

        jLabel29.setText("Tipos de Usuario:");

        jLabel31.setText("Id Usuario del sistema:");

        jLabel32.setText("Contraseña:");

        btnGuardarUsuario.setText("Guardar");

        btnEditarUsuario.setText("Editar");

        btnEliminarUsuario.setText("Eliminar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel29)
                                .addComponent(jLabel30)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel32))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTiposUsuariosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdUsuarioSistemaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(btnGuardarUsuario)
                        .addGap(58, 58, 58)
                        .addComponent(btnEditarUsuario)
                        .addGap(65, 65, 65)
                        .addComponent(btnEliminarUsuario)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtTiposUsuariosUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtIdUsuarioSistemaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtContraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarUsuario)
                    .addComponent(btnEditarUsuario)
                    .addComponent(btnEliminarUsuario))
                .addContainerGap())
        );

        TablaUsuario.setModel(modelTableUsuario);
        jScrollPane5.setViewportView(TablaUsuario);

        javax.swing.GroupLayout jPanelUsuariosLayout = new javax.swing.GroupLayout(jPanelUsuarios);
        jPanelUsuarios.setLayout(jPanelUsuariosLayout);
        jPanelUsuariosLayout.setHorizontalGroup(
            jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                .addGroup(jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabel28))
                    .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 806, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanelUsuariosLayout.setVerticalGroup(
            jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuarios", jPanelUsuarios);

        MenuArchivo.setText("Archivo");

        SubmenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        SubmenuSalir.setText("Salir");
        SubmenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmenuSalirActionPerformed(evt);
            }
        });
        MenuArchivo.add(SubmenuSalir);

        SubmenuAccionPersona.setText("Accion Persona");

        SubmenuBuscar.setText("Buscar");
        SubmenuAccionPersona.add(SubmenuBuscar);

        MenuArchivo.add(SubmenuAccionPersona);

        jMenuBar1.add(MenuArchivo);

        MenuEditar.setText("Editar");
        jMenuBar1.add(MenuEditar);

        MenuAcercade.setText("Acerca de");
        jMenuBar1.add(MenuAcercade);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SubmenuSalirActionPerformed

    private void btnGuardarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPersonaActionPerformed
        guardareditarpersona();
        if (controladorpersona.Guardarpersona(guardareditarpersona())) {
            JOptionPane.showMessageDialog(rootPane, "Persona guardado con exito en el sistema");
            limpiarComponentesPersona();
            modelTablePersona.setPersonas(controladorpersona.Obtenerpersonas());
            modelTablePersona.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnGuardarPersonaActionPerformed

    private void btnGuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedorActionPerformed
        guardareditarproveedor();
        if (controladorproveedor.GuardarProveedor(guardareditarproveedor())) {
            JOptionPane.showMessageDialog(rootPane, "Proveedor guardado con exito en el sistema");
            limpiarComponentesProveedores();
            modelTableProveedor.setProvedores(controladorproveedor.obtenerProveedores());
            modelTableProveedor.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnGuardarProveedorActionPerformed

    private void btnGuardarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarInventarioActionPerformed
        guardareditarinventario();
        if (controladorinventario.GuardarInventario(guardareditarinventario())) {
            JOptionPane.showMessageDialog(rootPane, "Producto guardado con exito en el sistema");
            limpiarComponentesInventario();
            modelTableInventario.setInventario(controladorinventario.ObtenerInventario());
            modelTableInventario.fireTableDataChanged();
        }
    }//GEN-LAST:event_btnGuardarInventarioActionPerformed

    private void btnComprobarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprobarCedulaActionPerformed
        if (!utilidades.validadorDeCedula(txtCedulaPersona.getText())) {
            JOptionPane.showMessageDialog(rootPane, "la cedula ingresada no es valida", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCedulaPersona.requestFocus();
        } else {
            JOptionPane.showMessageDialog(rootPane, "la cedula ingresada es valida");
            txtNombrePersona.requestFocus();
        }
    }//GEN-LAST:event_btnComprobarCedulaActionPerformed

    private void btnEditarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPersonaActionPerformed
        if (personaEditarEliminar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una Persona seleccionada para editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (personaEditarEliminar != null) {
            personaEditarEliminar = valoresactualizarPersona(personaEditarEliminar);
            if (controladorpersona.Editarpersona(personaEditarEliminar)) {
                JOptionPane.showMessageDialog(rootPane, "Persona editado con exito del sitema.");
                limpiarComponentesInventario();
                personaEditarEliminar = null;
                modelTablePersona.setPersonas(controladorpersona.Obtenerpersonas());
                modelTablePersona.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede editar la Persona", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarPersonaActionPerformed

    private void btnEditarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarInventarioActionPerformed
        if (inventarioeditar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una propducto seleccionado para editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (inventarioeditar != null) {
            inventarioeditar = valoresActualizarInventario(inventarioeditar);
            if (controladorinventario.EditarInventario(inventarioeditar)) {
                JOptionPane.showMessageDialog(rootPane, "Producto editado con exito del sitema.");
                limpiarComponentesInventario();
                inventarioeditar = null;
                modelTableInventario.setInventario(controladorinventario.ObtenerInventario());
                modelTableInventario.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede editar la Producto", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarInventarioActionPerformed

    private void btnEliminarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarInventarioActionPerformed
        if (inventarioeditar != null) {
            if (controladorinventario.EliminarInventario(inventarioeditar)) {
                JOptionPane.showMessageDialog(rootPane, "Producto eliminado con éxito del sitema.");
                limpiarComponentesInventario();
                inventarioeditar = null;
                modelTableInventario.setInventario(controladorinventario.ObtenerInventario());
                modelTableInventario.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar el producto seleccionado.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay producto seleccionada para eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarInventarioActionPerformed

    private void btnEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonaActionPerformed
        if (personaEditarEliminar != null) {
            if (controladorpersona.Eliminarpersona(personaEditarEliminar)) {
                JOptionPane.showMessageDialog(rootPane, "Persona eliminada con éxito del sitema.");
                limpiarComponentesPersona();
                personaEditarEliminar = null;
                modelTablePersona.setPersonas(controladorpersona.Obtenerpersonas());
                modelTablePersona.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar la Persona seleccionado.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay Persona seleccionada para eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarPersonaActionPerformed

    private void btnEditarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProveedorActionPerformed
        if (proveedoreditar == null) {
            JOptionPane.showMessageDialog(rootPane, "No hay una propducto seleccionado para editar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (proveedoreditar != null) {
            proveedoreditar = valoresActualizarProveedor(proveedoreditar);
            if (controladorproveedor.EditarProveedor(proveedoreditar)) {
                JOptionPane.showMessageDialog(rootPane, "Producto editado con exito del sitema.");
                limpiarComponentesInventario();
                proveedoreditar = null;
                modelTableProveedor.setProvedores(controladorproveedor.obtenerProveedores());
                modelTableInventario.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede editar la Producto", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEditarProveedorActionPerformed

    private void btnEliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProveedorActionPerformed
        if (proveedoreditar != null) {
            if (controladorproveedor.EliminarProveedores(proveedoreditar)) {
                JOptionPane.showMessageDialog(rootPane, "Proveedor eliminada con éxito del sitema.");
                limpiarComponentesProveedores();
                proveedoreditar = null;
                modelTableProveedor.setProvedores(controladorproveedor.obtenerProveedores());
                modelTableProveedor.fireTableDataChanged();
            } else {
                JOptionPane.showMessageDialog(rootPane, "No se puede eliminar el Proveedor seleccionado.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No hay Proveedor seleccionado para eliminar.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarProveedorActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed
        switch(cmbBoxPersona.getSelectedIndex()){
            case 0://Cedula
                modelTablePersona.setPersonas(controladorpersona.getPersonaCedulaLista(txtBuscarPersona.getText()));
                modelTablePersona.fireTableDataChanged();
                break;
            case 1://Telefono
                modelTablePersona.setPersonas(controladorpersona.getPersonaTelefonoLista(txtBuscarPersona.getText()));
                modelTablePersona.fireTableDataChanged();
                break;
        }
    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void btnBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProveedorActionPerformed
       switch(cmbbBoxProveedores.getSelectedIndex()){
           case 0://Ruc
               modelTableProveedor.setProvedores(controladorproveedor.ObtenerProveedoresRucLista(txtBuscarProveedor.getText()));
               modelTableProveedor.fireTableDataChanged();
               break;
           case 1://Telefono
               modelTableProveedor.setProvedores(controladorproveedor.ObtenerProveedoresTelefono(txtBuscarProveedor.getText()));
               modelTableProveedor.fireTableDataChanged();
               break;
       }
    }//GEN-LAST:event_btnBuscarProveedorActionPerformed

    private void btnBuscarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarInventarioActionPerformed
        switch(cmbBoxInventario.getSelectedIndex()){
            case 0:
                modelTableInventario.setInventario(controladorinventario.ObtenerInventarioCodigoLista(txtBuscarInventario.getText()));
                modelTableInventario.fireTableDataChanged();
                break;
            case 1:
                modelTableInventario.setInventario(controladorinventario.ObtenerInventarioCantidadLista(txtBuscarInventario.getText()));
                modelTableInventario.fireTableDataChanged();
                break;
        }
    }//GEN-LAST:event_btnBuscarInventarioActionPerformed

    private void btnAgregarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarVentasActionPerformed

    private void txtCedulaoRucClienteVentasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaoRucClienteVentasFocusLost
        Persona p= new Persona();
        controladorpersona.getNombreporCedula( p, txtCedulaoRucClienteVentas.getText());
        txtNombreClienteVentas.setText(p.getNombre());
        txtDireccionClienteVentas.setText(p.getDireccion());
        txtTelefonoClienteVentas.setText(p.getTelefono());
    }//GEN-LAST:event_txtCedulaoRucClienteVentasFocusLost

    public Persona guardareditarpersona() {
        if (txtCedulaPersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo cedula no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCedulaPersona.requestFocus();
            return null;
        }
        if (!utilidades.validadorDeCedula(txtCedulaPersona.getText())) {
            JOptionPane.showMessageDialog(rootPane, "la cedula ingresada no es valida", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCedulaPersona.requestFocus();
            return null;
        }
        if (txtNombrePersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo nombres no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNombrePersona.requestFocus();
            return null;
        }
        if (txtApellidoPersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo apellidos no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtApellidoPersona.requestFocus();
            return null;
        }
        if (txtDireccionPersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo direccion no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtDireccionPersona.requestFocus();
            return null;
        }
        if (txtCorreoPersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo correo no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCorreoPersona.requestFocus();
            return null;
        }
        if (!utilidades.validarcorreo(txtCorreoPersona.getText())) {
            JOptionPane.showMessageDialog(rootPane, "El campo correo no tiene arroba", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCorreoPersona.requestFocus();
        }
        if (txtTelefonoPersona.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo telefono no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtTelefonoPersona.requestFocus();
            return null;
        }
        if (!utilidades.validarNumeros(txtTelefonoPersona.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Los datos ingresados en el telefono no son validos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtTelefonoPersona.requestFocus();
            return null;
        }
        Persona persona = new Persona();
        persona.setCedula(txtCedulaPersona.getText());
        persona.setNombre(txtNombrePersona.getText());
        persona.setApellido(txtApellidoPersona.getText());
        persona.setDireccion(txtDireccionPersona.getText());
        persona.setTelefono(txtTelefonoPersona.getText());
        persona.setCorreo(txtCorreoPersona.getText());
        persona.setGenero(Integer.parseInt(txtGeneroPersona.getText()));
        return persona;
    }

    private Persona valoresactualizarPersona(Persona pe) {
        pe.setCedula(txtCedulaPersona.getText());
        pe.setNombre(txtNombrePersona.getText());
        pe.setApellido(txtApellidoPersona.getText());
        pe.setDireccion(txtDireccionPersona.getText());
        pe.setCorreo(txtCorreoPersona.getText());
        pe.setTelefono(txtTelefonoPersona.getText());
        pe.setGenero(Integer.parseInt(txtGeneroPersona.getText()));
        return pe;
    }

    public Proveedores guardareditarproveedor() {
        if (txtRucProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo RUC no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtRucProveedor.requestFocus();
            return null;
        }
        if (txtRazonSocialProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo Razon Social no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtRazonSocialProveedor.requestFocus();
            return null;
        }
        if (txtTipoActividadProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo Tipo de Actividad no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtTipoActividadProveedor.requestFocus();
            return null;
        }
        if (txtNombreRepresentanteLEgalProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo Nombre de representante legal no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtNombreRepresentanteLEgalProveedor.requestFocus();
            return null;
        }
        if (txtApellidoRepresentanteLegalProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo Apellido de representante legal no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtApellidoRepresentanteLegalProveedor.requestFocus();
            return null;
        }
        if (txtDireccionProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo correo no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtDireccionProveedor.requestFocus();
            return null;
        }
        if (txtTelefonoProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El telefono cedula no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtTelefonoProveedor.requestFocus();
            return null;
        }
        if (txtCorreoProveedor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo correo no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCorreoProveedor.requestFocus();
            return null;
        }
        Proveedores provedor = new Proveedores();
        provedor.setRuc(txtRucProveedor.getText());
        provedor.setRazonSocial(txtRazonSocialProveedor.getText());
        provedor.setTipoActividad(txtTipoActividadProveedor.getText());
        provedor.setNombreRepresentanteLegal(txtNombreRepresentanteLEgalProveedor.getText());
        provedor.setApellidosRepresentanteLegal(txtApellidoRepresentanteLegalProveedor.getText());
        provedor.setDireccion(txtDireccionProveedor.getText());
        provedor.setTelefono(txtTelefonoProveedor.getText());
        provedor.setCorreo(txtCorreoProveedor.getText());
        return provedor;
    }

    public Proveedores valoresActualizarProveedor(Proveedores p) {
        p.setRuc(txtRucProveedor.getText());
        p.setRazonSocial(txtRazonSocialProveedor.getText());
        p.setTipoActividad(txtTipoActividadProveedor.getText());
        p.setNombreRepresentanteLegal(txtNombreRepresentanteLEgalProveedor.getText());
        p.setApellidosRepresentanteLegal(txtApellidoRepresentanteLegalProveedor.getText());
        p.setDireccion(txtDireccionProveedor.getText());
        p.setTelefono(txtTelefonoProveedor.getText());
        p.setCorreo(txtCorreoProveedor.getText());
        return p;
    }

    public Inventario guardareditarinventario() {
        if (txtCodigoProductoInventario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo codigo de producto no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCodigoProductoInventario.requestFocus();
            return null;
        }
        if (txtDescripcionInventario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo descripcion no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtDescripcionInventario.requestFocus();
            return null;
        }
        if (txtCantidadProductoInventario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo precio de compra no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            txtCantidadProductoInventario.requestFocus();
            return null;
        }
        if (TxtComprasinIvatInventario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "El campo cantidad de prodictos no tiene datos", "ERROR", JOptionPane.ERROR_MESSAGE);
            TxtComprasinIvatInventario.requestFocus();
            return null;
        }
        Inventario inventario = new Inventario();
        inventario.setCodigoProducto(txtCodigoProductoInventario.getText());
        inventario.setDescripcion(txtDescripcionInventario.getText());
        inventario.setCantidadProductos(txtCantidadProductoInventario.getText());
//        inventario.setFechaCaducidad(SimpleDateFormat(TxtFechaCaducidadInventario.getText()));
        inventario.setPrecioCompraSinIVA(Double.parseDouble(TxtComprasinIvatInventario.getText()));
        inventario.setPrecioCompraConIV(Double.parseDouble(TxtCompraconIvaInventario.getText()));
        inventario.setPrecioMayorista(Double.parseDouble(TxtPrecioalMayorInventario.getText()));
        inventario.setPrecioClienteFijo(Double.parseDouble(TxtPrecioFijoInventario.getText()));
        inventario.setPrecioClienteNormal(Double.parseDouble(TxtPrecioNormalInventario.getText()));
        return inventario;
    }

    private Inventario valoresActualizarInventario(Inventario i) {
        i.setCodigoProducto(txtCodigoProductoInventario.getText());
        i.setDescripcion(txtDescripcionInventario.getText());
        i.setCantidadProductos(txtCantidadProductoInventario.getText());
//        i.setFechaCaducidad(SimpleDateFormat(TxtFechaCaducidadInventario.getText()));
        i.setPrecioCompraSinIVA(Double.parseDouble(TxtComprasinIvatInventario.getText()));
        i.setPrecioCompraConIV(Double.parseDouble(TxtCompraconIvaInventario.getText()));
        i.setPrecioMayorista(Double.parseDouble(TxtPrecioalMayorInventario.getText()));
        i.setPrecioClienteFijo(Double.parseDouble(TxtPrecioFijoInventario.getText()));
        i.setPrecioClienteNormal(Double.parseDouble(TxtPrecioNormalInventario.getText()));
        return i;
    }

    public void limpiarComponentesPersona() {
        txtCedulaPersona.setText("");
        txtNombrePersona.setText("");
        txtApellidoPersona.setText("");
        txtDireccionPersona.setText("");
        txtTelefonoPersona.setText("");
        txtCorreoPersona.setText("");
        txtGeneroPersona.setText("");
    }

    public void limpiarComponentesProveedores() {
        txtRucProveedor.setText("");
        txtRazonSocialProveedor.setText("");
        txtTipoActividadProveedor.setText("");
        txtNombreRepresentanteLEgalProveedor.setText("");
        txtApellidoRepresentanteLegalProveedor.setText("");
        txtDireccionProveedor.setText("");
        txtTelefonoProveedor.setText("");
        txtCorreoProveedor.setText("");
    }

    public void limpiarComponentesInventario() {
        txtCodigoProductoInventario.setText("");
        txtDescripcionInventario.setText("");
        txtCantidadProductoInventario.setText("");
        
        TxtComprasinIvatInventario.setText("");
        TxtCompraconIvaInventario.setText("");
        TxtPrecioalMayorInventario.setText("");
        TxtPrecioFijoInventario.setText("");
        TxtPrecioNormalInventario.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionContable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionContable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAcercade;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuEditar;
    private javax.swing.JMenu SubmenuAccionPersona;
    private javax.swing.JMenuItem SubmenuBuscar;
    private javax.swing.JMenuItem SubmenuSalir;
    private javax.swing.JTable TablaUsuario;
    private javax.swing.JTable TablePersona;
    private javax.swing.JTable TableProveedor;
    private javax.swing.JTable TableVentas;
    private javax.swing.JTextField TxtCompraconIvaInventario;
    private javax.swing.JTextField TxtComprasinIvatInventario;
    private javax.swing.JTextField TxtPrecioFijoInventario;
    private javax.swing.JTextField TxtPrecioNormalInventario;
    private javax.swing.JTextField TxtPrecioalMayorInventario;
    private javax.swing.JButton btnAgregarVentas;
    private javax.swing.JButton btnBuscarInventario;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnBuscarProveedor;
    private javax.swing.JButton btnComprobarCedula;
    private javax.swing.JButton btnEditarInventario;
    private javax.swing.JButton btnEditarPersona;
    private javax.swing.JButton btnEditarProveedor;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JButton btnEliminarInventario;
    private javax.swing.JButton btnEliminarPersona;
    private javax.swing.JButton btnEliminarProveedor;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnGuardarInventario;
    private javax.swing.JButton btnGuardarPersona;
    private javax.swing.JButton btnGuardarProveedor;
    private javax.swing.JButton btnGuardarUsuario;
    private javax.swing.JComboBox<String> cmbBoxInventario;
    private javax.swing.JComboBox<String> cmbBoxPersona;
    private javax.swing.JComboBox<String> cmbbBoxProveedores;
    private com.toedter.calendar.JDateChooser jDtCaducidadInventario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDatosPersona;
    private javax.swing.JPanel jPanelInventario;
    private javax.swing.JPanel jPanelPersona;
    private javax.swing.JPanel jPanelProveedores;
    private javax.swing.JPanel jPanelUsuarios;
    private javax.swing.JPanel jPanelVentas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton rdbCedula;
    private javax.swing.JRadioButton rdbPasaporte;
    private javax.swing.JTextField txtApellidoPersona;
    private javax.swing.JTextField txtApellidoRepresentanteLegalProveedor;
    private javax.swing.JTextField txtBuscarInventario;
    private javax.swing.JTextField txtBuscarPersona;
    private javax.swing.JTextField txtBuscarProveedor;
    private javax.swing.JTextField txtCantidadProductoInventario;
    private javax.swing.JTextField txtCantidadProductoVentas;
    private javax.swing.JTextField txtCedulaPersona;
    private javax.swing.JTextField txtCedulaoRucClienteVentas;
    private javax.swing.JTextField txtCodigoProductoInventario;
    private javax.swing.JTextField txtContraseñaUsuario;
    private javax.swing.JTextField txtCorreoPersona;
    private javax.swing.JTextField txtCorreoProveedor;
    private javax.swing.JTextField txtDescripcionInventario;
    private javax.swing.JTextField txtDireccionClienteVentas;
    private javax.swing.JTextField txtDireccionPersona;
    private javax.swing.JTextField txtDireccionProveedor;
    private javax.swing.JTextField txtFechaVentaVentas;
    private javax.swing.JTextField txtGeneroPersona;
    private javax.swing.JTextField txtIdUsuarioSistemaUsuario;
    private javax.swing.JTextField txtNombreClienteVentas;
    private javax.swing.JTextField txtNombrePersona;
    private javax.swing.JTextField txtNombreRepresentanteLEgalProveedor;
    private javax.swing.JTextField txtNotaVentaVentas;
    private javax.swing.JTextField txtProductoVentas;
    private javax.swing.JTextField txtRazonSocialProveedor;
    private javax.swing.JTextField txtRucProveedor;
    private javax.swing.JTextField txtTelefonoClienteVentas;
    private javax.swing.JTextField txtTelefonoPersona;
    private javax.swing.JTextField txtTelefonoProveedor;
    private javax.swing.JTextField txtTipoActividadProveedor;
    private javax.swing.JTextField txtTiposUsuariosUsuarios;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clickPersona(Persona p) {
        personaEditarEliminar = p;
        txtCedulaPersona.setText(p.getCedula());
        txtNombrePersona.setText(p.getNombre());
        txtApellidoPersona.setText(p.getApellido());
        txtDireccionPersona.setText(p.getTelefono());
        txtTelefonoPersona.setText(p.getDireccion());
        txtCorreoPersona.setText(p.getCorreo());
        txtGeneroPersona.setText(String.valueOf(p.getGenero()));
    }

    @Override
    public void clickInventario(Inventario i) {
        inventarioeditar = i;
        txtCodigoProductoInventario.setText(i.getCodigoProducto());
        txtDescripcionInventario.setText(i.getDescripcion());
        txtCantidadProductoInventario.setText(String.valueOf(i.getCantidadProductos()));
        TxtComprasinIvatInventario.setText(String.valueOf(i.getPrecioCompraSinIVA()));
        TxtCompraconIvaInventario.setText(String.valueOf(i.getPrecioCompraConIV()));
        TxtPrecioalMayorInventario.setText(String.valueOf(i.getPrecioMayorista()));
        TxtPrecioFijoInventario.setText(String.valueOf(i.getPrecioClienteFijo()));
        TxtPrecioNormalInventario.setText(String.valueOf(i.getPrecioClienteNormal()));
        jDtCaducidadInventario.setDate(i.getFechaCaducidad());
    }

    @Override
    public void clickProveedores(Proveedores pr) {
        proveedoreditar = pr;
        txtRucProveedor.setText(pr.getRuc());
        txtRazonSocialProveedor.setText(pr.getRazonSocial());
        txtTipoActividadProveedor.setText(pr.getTipoActividad());
        txtNombreRepresentanteLEgalProveedor.setText(pr.getNombreRepresentanteLegal());
        txtApellidoRepresentanteLegalProveedor.setText(pr.getApellidosRepresentanteLegal());
        txtDireccionProveedor.setText(pr.getDireccion());
        txtTelefonoProveedor.setText(pr.getTelefono());
        txtCorreoProveedor.setText(pr.getCorreo());
    }

    @Override
    public void clickTipoUsuario(TipoUsuario u) {
        usuarioeditar = u;
        txtTiposUsuariosUsuarios.setText(String.valueOf(u.getTipoUsuarioSistema()));
        txtIdUsuarioSistemaUsuario.setText(String.valueOf(u.getIdPersonaSistema()));
        txtContraseñaUsuario.setText(u.getContraseña());
    }

}
